name: ConsoleSpy
version: '${project.version}'
main: su.lxt3z.consolespy.Main
api-version: '1.16'
authors: [ lxt3z ]
depend: [ProtocolLib]
commands:
  console:
    usage: /console <on|off|hide|list|ignore [nick]>
    permission: console.use

permissions:
  console.use:
    default: op

  console.spy:
    default: op

  console.hide:
    default: op

  console.ignore:
    default: op

  console.reload:
    default: op
